services:
  - type: web
    name: catbox-uploader
    env: node
    buildCommand: |
      npm install -g bun
      bun install
      bun run build
    startCommand: bun index.ts
    envVars:
      - key: PORT
        value: 10000
    autoDeploy: true
